name: frontend
description: "Booking Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_dotenv: ^5.2.1

  get_it: ^8.0.3

  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  go_router: ^14.7.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
