version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    working_dir: /app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/booking
    volumes:
      - ./backend:/app
    command: "npm run dev"

volumes:
  mongo_data:
